inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/AbcSize:
  Exclude:
    - 'lib/ldp/container.rb'
    - 'lib/ldp/resource.rb'
    - 'lib/ldp/client/methods.rb'

Metrics/BlockLength:
  Exclude:
    - 'ldp.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'lib/ldp/resource.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/ldp/container.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/ldp/client/methods.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/ldp/container.rb'
    - 'lib/ldp/resource.rb'
    - 'lib/ldp/client/methods.rb'

Naming/FileName:
  Exclude:
    - 'Gemfile'

Naming/PredicateName:
  Exclude:
   - '**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/integration/integration_spec.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

