version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.0.1
      ruby_type:
        type: string
        default: ruby
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
      ruby_type: << parameters.ruby_type >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    working_directory: ~/project
    steps:
      - run: sudo apt-get update && sudo apt-get install libgmp-dev

      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.5
          rails_version: 6.0.4.4
      - bundle_and_test:
          name: ruby2-6_rails6-0
          ruby_version: 2.6.9
          rails_version: 6.0.4.4
      - bundle_and_test:
          name: ruby2-5_rails6-0
          ruby_version: 2.5.9
          rails_version: 6.0.4.4
      - bundle_and_test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.5
          rails_version: 5.2.6
      - bundle_and_test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.9
          rails_version: 5.2.6
      - bundle_and_test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.9
          rails_version: 5.2.6
      - bundle_and_test:
          name: ruby2-4_rails5-2
          ruby_version: 2.4.10
          rails_version: 5.2.6
      - bundle_and_test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - bundle_and_test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.9
          rails_version: 5.1.7
      - bundle_and_test:
          name: ruby2-5_rails5-1
          ruby_version: 2.5.9
          rails_version: 5.1.7
      - bundle_and_test:
          name: ruby2-4_rails5-1
          ruby_version: 2.4.10
          rails_version: 5.1.7
